apiVersion: v1
kind: ConfigMap
metadata:
  name: desker-grafana-datasource
  namespace: team-6-ns
data:
  prometheus.yml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://desker-prometheus:9090
        isDefault: true
        editable: true
