apiVersion: v1
kind: PersistentVolume
metadata:
  name: desker-sqlite-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /var/lib/team-6/desker-sqlite
    type: DirectoryOrCreate