apiVersion: v1
kind: Secret
metadata:
  name: {{ include "desker-backend.fullname" . }}-secret
type: Opaque
stringData:
  JWT_SECRET: {{ .Values.app.jwtSecret | quote }}
  SMTP_HOST: {{ .Values.smtp.host | quote }}
  SMTP_PORT: {{ .Values.smtp.port | quote }}
  SMTP_USERNAME: {{ .Values.smtp.username | quote }}
  SMTP_PASSWORD: {{ .Values.smtp.password | quote }}
  SMTP_FROM: {{ .Values.smtp.from | quote }}
